// <auto-generated />
namespace PangusServices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _operator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_operator));
        
        string IMigrationMetadata.Id
        {
            get { return "201511151000119_operator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
